parameters:
#    zcms_commentaire.example.class: Zcms\CommentaireBundle\Example

services:
    zcms_commentaire.twig.extension:
        class: Zcms\CommentaireBundle\Extension\CommentaireExtension
        tags:
            - { name: twig.extension }
