<?php

namespace Zcms\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository {

    public function getDerniersArticles($limite = null) {
        
        $qb = $this->createQueryBuilder('b')
                ->select('b')
                ->where('b.active = 1')
                ->addOrderBy('b.dateCreation', 'DESC');

        if (false === is_null($limite))
            $qb->setMaxResults($limite);

        return $qb->getQuery()->getResult();
    }

}