<?php

namespace Zcms\CommentaireBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository {

    public function getCommentairesArticle($articleId, $approuve = true) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.article = :article_id')
                ->addOrderBy('c.dateCreation')
                ->setParameter('article_id', $articleId);

        if (false === is_null($approuve))
            $qb->andWhere('c.approuve = :approuve')
                    ->setParameter('approuve', $approuve);

        return $qb->getQuery()
                        ->getResult();
    }

}