ZcmsFrontendBundle_homepage:
    pattern:  /
    defaults: { _controller : ZcmsFrontendBundle:Index:index }

ZcmsFrontendBundle_demo:
    pattern:  /demo
    defaults: { _controller : ZcmsFrontendBundle:Demo:index }

ZcmsArticle_crud:
    resource: "routing/article.yml"
    prefix:   /crud

