ZcmsFrontendBundle_homepage:
    pattern:  /
    defaults: { _controller : ZcmsFrontendBundle:Index:index }

ZcmsFrontendBundle_demo:
    pattern:  /demo
    defaults: { _controller : ZcmsFrontendBundle:Demo:index }

ZcmsArticle_crud:
    resource: "routing/article.yml"
    prefix:   /crud

ZcmsFrontendBundle_commentaire_creation:
    pattern:  /commentaire/{article_id}
    defaults: { _controller: ZcmsFrontendBundle:Commentaire:creation }
    requirements:
        _method:  POST
        article_id: \d+