parameters:
#    zcms_frontend.example.class: Zcms\FrontendBundle\Example

services:
#    zcms_frontend.example:
#        class: %zcms_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
